import CapacityAtlasForMathlib.InformationTheory.BinaryWords
import Mathlib

#check Equiv.piFinSucc
#check Fintype.sum_equiv
#check Fintype.prod_equiv
#check Fintype.sum_prod_type
#check Fintype.prod_sum
#check Fin.sum_univ_succ
#check Fin.prod_univ_succ
#check Fin.cons
#check Fin.tail
#check Fin.consEquiv
#check Fin.insertNth
#check Finset.sum_mul
#check Finset.mul_sum
#check Real.logb_mul
#check Real.logb_rpow
#check Real.rpow_logb
#check Real.rpow_le_rpow
#check Real.strictMono_rpow_of_base_gt_one
#check Nat.ceil
#check Nat.le_ceil
#check Nat.ceil_le
#check Nat.ceil_lt_add_one
#check Real.logb_pow
#check Real.logb_two
#check Real.logb_self_eq_one
#check Finset.sum_le_card_nsmul
#check Finset.card_filter_le
